# Generated by Django 3.2.14 on 2022-07-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_id', models.IntegerField(unique=True)),
                ('fuel_tank', models.IntegerField(help_text='Amount of fuel tank')),
                ('consumption', models.FloatField(help_text='Fuel consumption per minute')),
                ('passengers', models.IntegerField(help_text='Amount of passengers on board')),
            ],
        ),
    ]
