# Generated by Django 3.2.14 on 2022-07-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='minutes_to_fly',
            field=models.PositiveIntegerField(default=0, help_text='minutes to fly'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airplane',
            name='airplane_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='fuel_tank',
            field=models.PositiveIntegerField(help_text='Amount of fuel tank'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='passengers',
            field=models.PositiveIntegerField(help_text='Amount of passengers on board'),
        ),
    ]
